export type PaletteItem = {
  type: string;
  name: string;
  category: string;
  defaults?: Record<string, unknown>;
};

export const NODE_PALETTE: PaletteItem[] = [
  // Browser
  { type: "open_url", name: "Open URL", category: "Browser", defaults: { url: "{{variable.baseUrl}}" } },
  { type: "click", name: "Click", category: "Browser", defaults: { role: "button", name: "Submit" } },
  { type: "fill_input", name: "Fill Input", category: "Browser", defaults: { label: "Username", value: "{{variable.username}}" } },
  { type: "select_option", name: "Select Option", category: "Browser" },
  { type: "press_key", name: "Press Key", category: "Browser", defaults: { key: "Enter" } },
  { type: "wait_for_element", name: "Wait for Element", category: "Browser" },
  { type: "wait_for_page_state", name: "Wait for Page State", category: "Browser" },
  { type: "wait_for_aspx_postback", name: "Wait for ASPX Postback Completion", category: "Browser" },
  { type: "wait_for_react_render", name: "Wait for React Render", category: "Browser" },
  { type: "wait_for_element_stability", name: "Wait for Element Stability", category: "Browser" },
  { type: "wait_for_network_response", name: "Wait for Network Response", category: "Browser" },
  { type: "wait_for_loading_indicator", name: "Wait for Loading Indicator to Disappear", category: "Browser" },
  { type: "wait_for_route_change", name: "Wait for Route Change", category: "Browser" },
  { type: "extract_text", name: "Extract Text", category: "Browser", defaults: { outputKey: "text" } },
  { type: "extract_attribute", name: "Extract Attribute", category: "Browser" },
  { type: "take_screenshot", name: "Take Screenshot", category: "Browser" },
  { type: "upload_file", name: "Upload File", category: "Browser" },
  { type: "download_file", name: "Download File", category: "Browser" },
  { type: "switch_tab", name: "Switch Tab", category: "Browser" },
  { type: "close_tab", name: "Close Tab", category: "Browser" },
  { type: "assert_visible", name: "Assert Visible", category: "Browser" },
  { type: "assert_hidden", name: "Assert Hidden", category: "Browser" },
  { type: "assert_text", name: "Assert Text", category: "Browser" },
  { type: "assert_url", name: "Assert URL", category: "Browser" },
  { type: "assert_element_count", name: "Assert Element Count", category: "Browser" },
  { type: "assert_field_value", name: "Assert Field Value", category: "Browser" },
  { type: "execute_javascript", name: "Execute JavaScript", category: "Browser" },
  // Auth / verification
  {
    type: "wait_for_email",
    name: "Wait for Email",
    category: "Auth",
    defaults: {
      imapHostSecret: "IMAP_HOST",
      usernameSecret: "IMAP_USERNAME",
      passwordSecret: "IMAP_PASSWORD",
      folder: "INBOX",
      subjectContains: "verification",
      unreadOnly: true,
      timeoutSeconds: 180,
      pollIntervalSeconds: 5,
    },
  },
  {
    type: "extract_email_otp",
    name: "Extract OTP from Email",
    category: "Auth",
    defaults: { outputKey: "otp" },
  },
  {
    type: "extract_email_verification_link",
    name: "Extract Verification Link",
    category: "Auth",
    defaults: { urlContains: "verify", outputKey: "verificationUrl" },
  },
  {
    type: "open_verification_link",
    name: "Open Verification Link",
    category: "Auth",
    defaults: { url: "{{node.extract-link.output.verificationUrl}}" },
  },
  {
    type: "generate_totp",
    name: "Generate TOTP",
    category: "Auth",
    defaults: { secretKey: "TOTP_SECRET", digits: 6, intervalSeconds: 30, outputKey: "otp" },
  },
  {
    type: "verify_totp",
    name: "Verify TOTP",
    category: "Auth",
    defaults: { secretKey: "TOTP_SECRET", code: "{{node.otp.output.otp}}" },
  },
  {
    type: "human_otp_input",
    name: "Human OTP Input",
    category: "Auth",
    defaults: {
      prompt: "Enter the OTP from SMS / authenticator / email",
      hint: "Workflow will pause until you submit the code",
      timeoutSeconds: 600,
    },
  },
  {
    type: "fill_otp",
    name: "Fill OTP Field",
    category: "Auth",
    defaults: {
      label: "OTP",
      value: "{{node.otp.output.otp}}",
      placeholder: "Enter code",
    },
  },
  // CLI
  { type: "run_bash", name: "Run Bash", category: "CLI", defaults: { shell: "bash", command: "echo hello" } },
  { type: "run_powershell", name: "Run PowerShell", category: "CLI", defaults: { shell: "powershell", command: "Write-Output 'hello'" } },
  { type: "run_cmd", name: "Run CMD", category: "CLI", defaults: { shell: "cmd", command: "echo hello" } },
  { type: "run_python_script", name: "Run Python Script", category: "CLI", defaults: { shell: "python", script: "print('ok')" } },
  { type: "run_node_command", name: "Run Node Command", category: "CLI", defaults: { shell: "node", script: "console.log('ok')" } },
  { type: "run_custom_executable", name: "Run Custom Executable", category: "CLI", defaults: { executable: "echo" } },
  // API
  { type: "rest_request", name: "REST Request", category: "API", defaults: { method: "GET", url: "{{variable.baseUrl}}{{variable.healthEndpoint}}" } },
  { type: "assert_status_code", name: "Assert Status Code", category: "API", defaults: { expected: 200 } },
  { type: "assert_json_value", name: "Assert JSON Value", category: "API" },
  { type: "extract_json_value", name: "Extract JSON Value", category: "API" },
  { type: "validate_json_schema", name: "Validate JSON Schema", category: "API" },
  // Database
  { type: "execute_query", name: "Execute Query", category: "Database" },
  { type: "execute_command", name: "Execute Command", category: "Database" },
  { type: "extract_scalar_value", name: "Extract Scalar Value", category: "Database" },
  { type: "extract_rows", name: "Extract Rows", category: "Database" },
  { type: "assert_row_count", name: "Assert Row Count", category: "Database" },
  { type: "assert_column_value", name: "Assert Column Value", category: "Database" },
  { type: "file_exists", name: "File Exists", category: "Files" },
  { type: "file_content_assertion", name: "File Content Assertion", category: "Files" },
  { type: "collect_files", name: "Collect Files", category: "Files" },
  // Logic
  { type: "start", name: "Start", category: "Logic" },
  { type: "end", name: "End", category: "Logic" },
  { type: "if_else", name: "If / Else", category: "Logic" },
  { type: "loop", name: "Loop", category: "Logic" },
  { type: "for_each", name: "For Each", category: "Logic" },
  { type: "retry", name: "Retry", category: "Logic" },
  { type: "wait", name: "Wait", category: "Logic", defaults: { seconds: 1 } },
  { type: "parallel_branch", name: "Parallel Branch", category: "Logic" },
  { type: "merge", name: "Merge", category: "Logic" },
  { type: "set_variable", name: "Set Variable", category: "Logic" },
  { type: "transform_variable", name: "Transform Variable", category: "Logic" },
  { type: "call_sub_workflow", name: "Call Sub-workflow", category: "Logic" },
  { type: "stop_workflow", name: "Stop Workflow", category: "Logic" },
  // Validation
  { type: "compare_values", name: "Compare Values", category: "Validation" },
  { type: "regex_match", name: "Regex Match", category: "Validation" },
  { type: "json_assertion", name: "JSON Assertion", category: "Validation" },
  { type: "file_exists", name: "File Exists", category: "Validation" },
  { type: "file_content_assertion", name: "File Content Assertion", category: "Validation" },
  { type: "exit_code_assertion", name: "Exit Code Assertion", category: "Validation" },
  { type: "numeric_threshold", name: "Numeric Threshold", category: "Validation" },
  // Evidence
  { type: "capture_screenshot", name: "Capture Screenshot", category: "Evidence" },
  { type: "save_browser_trace", name: "Save Browser Trace", category: "Evidence" },
  { type: "save_console_logs", name: "Save Console Logs", category: "Evidence" },
  { type: "save_network_logs", name: "Save Network Logs", category: "Evidence" },
  { type: "save_cli_output", name: "Save CLI Output", category: "Evidence" },
  { type: "collect_files", name: "Collect Files", category: "Evidence" },
  { type: "create_execution_summary", name: "Create Execution Summary", category: "Evidence" },
  // Integration
  { type: "create_workboard_item", name: "Create OneOpen Workboard Item", category: "Integration" },
  { type: "add_workboard_comment", name: "Add Comment to Workboard Item", category: "Integration" },
  { type: "attach_execution_evidence", name: "Attach Execution Evidence", category: "Integration" },
  { type: "send_webhook", name: "Send Webhook", category: "Integration" },
];
